name: Build APK with Docker Step

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build APK inside Docker Container
      run: |
        # تشغيل الدوكر مباشرة وتمرير مجلد المشروع الحالي لداخله لبناء التطبيق
        docker run --rm -v ${{ github.workspace }}:/home/developer/app ahmedrowaihi/buildozer:latest android debug
