name: Build APK with Docker Official

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    # استخدام الحاوية الرسمية المضمونة والمفتوحة من شركة Kivy مباشرة
    container:
      image: ghcr.io/kivy/buildozer:master

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build APK
      run: |
        # تشغيل البناء داخل بيئة كيوي الرسمية المعزولة
        buildozer android debug
